# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PotatoParty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PotatoParty
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SnapKit', '~> 3.0'
end
